/** \file var.c

Contains the function that connects the string of the parameter file to global variables.
The var() function is found in Interpret.c

*/

#define __LOCAL
#include "fargo.h"
#undef __LOCAL

void InitVariables() {
  var("DT", &DT, REAL, YES, "1.");
  var("SIGMA0", &SIGMA0, REAL, YES, "173.");
  var("NINTERM", &NINTERM, INT, YES, "10.");
  var("NTOT", &NTOT, INT, YES, "1501.");
  var("OUTPUTDIR", OUTPUTDIR, STRING, YES, "~masset");
  var("INNERBOUNDARY", INNERBOUNDARY, STRING, NO, "NONE");
  var("OUTERBOUNDARY", OUTERBOUNDARY, STRING, NO, "NONE");
  var("LABELADVECTION", ADVLABEL, STRING, NO, "NO");
  var("TRANSPORT", TRANSPORT, STRING, NO, "FAST");
  var("PLANETCONFIG", PLANETCONFIG, STRING, NO, "Systems/SolarSystem.cfg");
  var("COREACCCONFIG", COREACCCONFIG, STRING, NO, "");
  var("MASSTAPER", &MASSTAPER, REAL, NO, "0.0000001");
  var("RADIALSPACING", GRIDSPACING, STRING, NO, "ARITHMETIC");
  var("NRAD", &NRAD, INT, YES, "64.0");
  var("NSEC", &NSEC, INT, YES, "64.0");
  var("RMIN", &RMIN, REAL, YES, "1.0");
  var("RMAX", &RMAX, REAL, YES, "1.0");
  var("THICKNESSSMOOTHING", &THICKNESSSMOOTHING, REAL, NO, "0.0");
  var("ROCHESMOOTHING", &ROCHESMOOTHING, REAL, NO, "0.0");
  var("ASPECTRATIO", &ASPECTRATIO, REAL, YES, "0.05");
  var("VISCOSITY", &VISCOSITY, REAL, NO, "0.0");  
  var("ALPHAVISCOSITY", &ALPHAVISCOSITY, REAL, NO, "0.0");  
  var("SIGMASLOPE", &SIGMASLOPE, REAL, YES, "0.0");  
  var("RELEASERADIUS", &RELEASERADIUS, REAL, NO, "0.0");  
  var("RELEASEDATE", &RELEASEDATE, REAL, NO, "0.0");  
  var("OMEGAFRAME", &OMEGAFRAME, REAL, NO, "0.0");
  var("DISK", DISK, STRING, NO, "YES");
  var("FRAME", FRAME, STRING, NO, "FIXED");
  var("OUTERSOURCEMASS", OUTERSOURCEMASS, STRING, NO, "NO");
  var("WRITEDENSITY", WRITEDENSITY, STRING, NO, "YES");
  var("WRITEVELOCITY", WRITEVELOCITY, STRING, NO, "YES");
  var("WRITEENERGY", WRITEENERGY, STRING, NO, "YES");
  var("WRITEPOTENTIAL", WRITEPOTENTIAL, STRING, NO, "NO");
  var("WRITETEMP", WRITETEMP, STRING, NO, "NO");
  var("WRITEDISKHEIGHT", WRITEDISKHEIGHT, STRING, NO, "NO");  
  var("WRITESOUNDSPEED", WRITESOUNDSPEED, STRING, NO, "NO");  
  var("INDIRECTTERM", INDIRECTTERM, STRING, NO, "YES");
  var("IMPOSEDDISKDRIFT", &IMPOSEDDISKDRIFT, REAL, NO, "0.0");
  var("FLARINGINDEX", &FLARINGINDEX, REAL, NO, "0.0");
  var("ECCENTRICITY", &ECCENTRICITY, REAL, NO, "0.0");
  var("CAVITYRADIUS", &CAVITYRADIUS, REAL, NO, "0.0");
  var("CAVITYRATIO", &CAVITYRATIO, REAL, NO, "1.0");
  var("CAVITYWIDTH", &CAVITYWIDTH, REAL, NO, "1.0");
  var("TRANSITIONRADIUS", &TRANSITIONRADIUS, REAL, NO, "0.0");
  var("TRANSITIONRATIO", &TRANSITIONRATIO, REAL, NO, "1.0");
  var("TRANSITIONWIDTH", &TRANSITIONWIDTH, REAL, NO, "1.0");
  var("LAMBDADOUBLING", &LAMBDADOUBLING, REAL, NO, "0.0");

  // GFARGO2 parameters
  //------------------------------------------------------------------------------
  var("EXCLUDEHILL", EXCLUDEHILL, STRING, NO, "NO");
  var("HEAVISIDEB", &HEAVISIDEB, REAL, NO, "1.0");
  var("DAMPRMIN", &DAMPRMIN, REAL, NO, "1.05");
  var("DAMPRMAX", &DAMPRMAX, REAL, NO, "0.9");
  var("DENSITYFLOOR", &DENSITYFLOOR, REAL, NO, "0.0");
  var("SELFGRAVITY", SELFGRAVITY, STRING, NO, "NO");
  var("SIGMACUTOFFRADIN", &SIGMACUTOFFRADIN, REAL, NO, "0.0");
  var("SIGMACUTOFFRADOUT", &SIGMACUTOFFRADOUT, REAL, NO, "0.0");

  var("VISCOUTFLOWFRAC", &VISCOUTFLOWFRAC, REAL, NO, "1.0");
  var("SIMNAME", SIMNAME, STRING, YES, "UNDEF");
  var("WINSIZE", &WINSIZE, INT, NO, "512");
  
  var("DUSTGRID", DUSTGRID, STRING, NO, "NO"); 
  var("DUSTGROWTH", DUSTGROWTH, STRING, NO, "NO");
  var("DUSTCONSTSTOKES", DUSTCONSTSTOKES, STRING, NO, "NO");
  var("DUSTFEEDBACK", DUSTFEEDBACK, STRING, NO, "NO"); 
  var("DUSTSELFGRAVITY", DUSTSELFGRAVITY, STRING, NO, "NO");   
  var("DUSTSIZEBIN", DUSTSIZEBIN, STRING, NO, "");
  var("DUSTMASSBIN", DUSTMASSBIN, STRING, NO, "");
  var("DUSTBULKDENS", &DUSTBULKDENS, REAL, NO, "3.0");
  var("DUSTVFRAG", &DUSTVFRAG, REAL, NO, "0.0");
  var("MASSUNIT", &MASSUNIT, REAL, NO, "1.0");
    
  // adaptive alpha viscosity
  var("ADAPTIVEVISCOSITY", ADAPTIVEVISCOSITY, STRING, NO, "NO"); 
  var("ALPHAVISCOSITYDEAD", &ALPHAVISCOSITYDEAD, REAL, NO, "0.0");
  var("ALPHASMOOTH", &ALPHASMOOTH, REAL, NO, "0.0");
  var("ALPHASIGMATHRESH", &ALPHASIGMATHRESH, REAL, NO, "0.0");  

  // adibatic
  var("ADIABATIC", ADIABATIC, STRING, NO, "NO"); 
  var("ADIABATICINDEX", &ADIABATICINDEX, REAL, NO, "0.0");
  var("COOLING", COOLING, STRING, NO, "NO");
  var("COOLINGTIME0", &COOLINGTIME0, REAL, NO, "0.0");
  var("VISCHEATING", VISCHEATING, STRING, NO, "NO"); 
  var("CFL", &CFL, REAL, YES, "0.5");

  // static viscosity transition
  var("DEADZONE", DEADZONE, STRING, NO, "NO"); 
  var("DEADZONERIN", &DEADZONERIN, REAL, NO, "-1.0");
  var("DEADZONEDELTARIN", &DEADZONEDELTARIN, REAL, NO, "-1.0");
  var("DEADZONEROUT", &DEADZONEROUT, REAL, NO, "-1.0");
  var("DEADZONEDELTAROUT", &DEADZONEDELTAROUT, REAL, NO, "-1.0");
  var("DEADZONEALPHA", &DEADZONEALPHA, REAL, NO, "-1.0");

  var("ZEROVELRAD", ZEROVELRAD, STRING, NO, "NO"); 

  // nebula model
  var("NEBULA", NEBULA, STRING, NO, "NO");
  var("NEBULAMASS", &NEBULAMASS, REAL, NO, "0.0");
  var("NEBULAEXT", &NEBULAEXT, REAL, NO, "0.0");
  var("NEBULAPOSX", &NEBULAPOSX, REAL, NO, "0.0");
  var("NEBULAPOSY", &NEBULAPOSY, REAL, NO, "0.0");
  var("NEBULAVELX", &NEBULAVELX, REAL, NO, "0.0");
  var("NEBULAVELY", &NEBULAVELY, REAL, NO, "0.0");
  var("NEBULATEMP", &NEBULATEMP, REAL, NO, "0.0");

  //------------------------------------------------------------------------------
#ifdef FARGO_INTEGRATION
//  var("GASCUBICOVERSAMP", &GASCUBICOVERSAMP, INT, YES, "1");
  var("GASOVERSAMPRAD", &GASOVERSAMPRAD, INT, YES, "1");
  var("GASOVERSAMPAZIM", &GASOVERSAMPAZIM, INT, YES, "1");
  var("DUSTCUBICUNDERSAMP", &DUSTCUBICUNDERSAMP, INT, YES, "1");
  var("HIPRELEASEDATE", &HIPRELEASEDATE, REAL, NO, "0.0");  
  var("NBODY_SUBDT", &NBODY_SUBDT, INT, NO, "1.0");
  var("DUSTFEEDBACKDRAG", DUSTFEEDBACKDRAG, STRING, NO, "NO");
  var("DUSTFEEDBACKGRAV", DUSTFEEDBACKGRAV, STRING, NO, "NO");  
#endif
}

